# Site settings
title: Jyoti Mishra
email:  09mishra.jyoti@gmail.com
url: https://jstjyoti.github.io
plugins:
  - jekyll-sitemap
description: "Portfolio of Jyoti Mishra"
keywords: "Portfolio, Resume"
skills: "Coder, Developer, Problem Solver"
meta_author: Jyoti Mishra

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 80B3FF
  primary-rgb: "128,179,255"
  secondary: FD6E8A
  secondary-dark: A2122F

# Footer settings
footer:
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Jyoti_Mi
  - title: linkedin
    url: https://www.linkedin.com/in/jyoti-mishra-56a25415b/
  - title: github
    url: http://github.com/jstjyoti

# Postal address (add as many lines as necessary)
address:
  - line: 32/H Kundan Bye Lane, Liluah, Howrah, West Bengal - 711204, India

# Build settings
markdown: kramdown
permalink: pretty
